name:  Kit
version:  1.0
main:  me.chocoaa.kit.Kit
description:  A very simple kit plugin
depend: [Vault]

commands:
     kit:
        usage: /<command>
        description: Get a kit.
     clearinventory	:
        usage: /<command>
        aliases: [clearinv, ci,]
        description: Empty your inventory.
        